name: Build and deploy Node.js app to Azure Web App - appsiode

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_RPP_API_BASE: ${{ secrets.NEXT_PUBLIC_RPP_API_BASE }}
          NEXT_PUBLIC_SICE_API_BASE: ${{ secrets.NEXT_PUBLIC_SICE_API_BASE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          API_AUTH_URL: ${{ secrets.API_AUTH_URL }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68FEA924AD5D4AB098AB077B0058AAAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB4561F4E0FD40CD9FA152B529451D65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4298F23AEB8742E6AB779878A309BA57 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appsiode'
          slot-name: 'Production'
          package: . # Sube TODO: .next, node_modules y package.json